Changed contributing guide to href to 2.5 instead of 2.2
SFML/SFML-Website pull request #158
Opened 2022-12-23 19:59 UTC by dogunbound

Just some things that need to be updated

2022-12-24 00:30 UTC, eXpl0it3r requested changes
Ohh, thanks for spotting that! With `/latest/` we can prevent future occurrence.

2022-12-24 00:30 UTC, eXpl0it3r commented on contribute.php
> + <li>Make sure it is really a bug and not a misunderstanding of what SFML is supposed to do. Check the <a href="documentation/2.5.1/">documentation</a> again to be sure.</li>
Can you use `/latest/` instead?

2022-12-24 00:30 UTC, eXpl0it3r commented on contribute.php
> + <li>Use the <a href="https://github.com/SFML/SFML">latest revision</a> from GitHub and check if the bug has not already been fixed. Refer to the <a href="tutorials/2.5/compile-with-cmake.php">offici
Can you use `/latest/` instead?

2022-12-24 04:07 UTC, dogunbound commented on contribute.php
> + <li>Make sure it is really a bug and not a misunderstanding of what SFML is supposed to do. Check the <a href="documentation/2.5.1/">documentation</a> again to be sure.</li>
Done

2022-12-24 04:07 UTC, dogunbound commented on contribute.php
> + <li>Use the <a href="https://github.com/SFML/SFML">latest revision</a> from GitHub and check if the bug has not already been fixed. Refer to the <a href="tutorials/2.5/compile-with-cmake.php">offici
Done

2022-12-24 06:39 UTC, eXpl0it3r approved these changes

2022-12-29 13:43 UTC, merged

2022-12-29 13:43 UTC, eXpl0it3r commented
Thanks for the fix! 🙂